const types = {
  UPDATE_FORM: '@shop/UPDATE_FORM',
  GET_OFFERS: '@shop/GET_OFFERS',
  SET_OFFERS: '@shop/SET_OFFERS',
  UPDATE_SUBSCRIPTION: '@shop/UPDATE_SUBSCRIPTION',
  UPDATE_SUBSCRIPTION_RESPONSE: '@shop/UPDATE_SUBSCRIPTION_RESPONSE',
  SAVE_SUBSCRIPTION: '@shop/SAVE_SUBSCRIPTION',
};

export default types;
